language: node_js

node_js:
  - stable

notifications:
  email:
    - sanchezjjose@gmail.com

install:
  - npm install

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
